project: default
source:
  repoURL: 'https://github.com/kosh000/kube_argo.git'
  path: canary
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: docuseal-ns
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
