apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-canary-myapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kosh000/kube_argo.git
    targetRevision: HEAD
    path: canary
  destination: 
    server: https://kubernetes.default.svc
    namespace: rollout-canary-myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true