---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-docuseal
  namespace: docuseal-ns
spec:
  template:
    metadata:
      labels:
        app: docuseal
    spec:
      containers:
      - name: docuseal
        image: docuseal/docuseal:1.4.9
        ports:
        - containerPort: 3000
  selector:
    matchLabels:
      app: docuseal
  replicas: 10
  revisionHistoryLimit: 2
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {} # rollout manually
