apiVersion: apps/v1
kind: Rollout
metadata:
  name: rollout-canary-myapp
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary-myapp
  template:
    metadata:
      labels:
        app: rollout-canary-myapp
    spec:
      containers:
      - name: myapp
        image: docuseal/docuseal
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  strategy:
    canary:
      steps:
      - experiment:
          templates:
          - name: myapp-canary
            specRef: canary
            selector:
              matchLabels:
                app: rollout-canary-myapp
            metadata:
              labels:
                app: rollout-canary-myapp