---
# The rollout-canary-preview service will point to the preview stack, making them reachable without
# exposing them to production traffic.
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary-preview
spec:
  selector:
    app: rollout-canary-preview
  ports:
  - protocol: TCP
    targetPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary-production
spec:
  selector:
    app: rollout-canary-production
  ports:
  - protocol: TCP
    targetPort: 3000