---

apiVersion: v1
kind: Service
metadata:
  name: docuseal-svc
  namespace: docuseal-ns
spec:
  selector:
    app: docuseal
  ports:
  - protocol: TCP
    targetPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary-production
spec:
  selector:
    app: rollout-canary-production
  ports:
  - protocol: TCP
    targetPort: 3000